architecture:
  model_name: google/vit-base-patch16-224-in21k
  freeze: true
  dropout: 0.1
  learning_rate: 0.003
  weight_decay: 0.001
  warmup_steps: 1
  max_steps: 1

checkpointing:
  dirpath: ""
  monitor: "val/acc"
  mode: "max"
  save_top_k: 3
  save_last: True
  verbose: True
